export const MERCHANTS = 'MERCHANTS';
export const MERCHANTS_CREATE_START = 'MERCHANTS_CREATE_START';
export const MERCHANTS_CREATE_SUCCESS = 'MERCHANTS_CREATE_SUCCESS';
export const MERCHANTS_CREATE_ERROR = 'MERCHANTS_CREATE_ERROR';
export const MERCHANTS_DESTROY_TEMP = 'MERCHANTS_DESTROY_TEMP';
